### ISSUE TITLE
Support for filtering the slices

### ISSUE THREAD

**Issue by prabhu** [AppThreat/atom#4]
We need a way of customizing the slicing operation to limit the data that gets written to the slices json.

Usages slices
-------------

- [x] Accept method filters to filter methods such as constructors, getters or setters method etc based on pattern
- [x] Accept parameter filters to filter based on parameter types
- [x] Accept annotation filters to filter methods based on annotations

DataFlow slices
---------------

- [ ] Limit dataflows to only those that begin from an internal method
- [x] Limit dataflows to only those that end with an external method
- [ ] Options to accept patterns for sources
- [x] Options to accept patterns for sinks

Common
-------

- [ ] Accept a yaml configuration to pass the parameters for the filtering operations
- [ ] Add safeguards to prevent arbitrary remote code execution and exfiltration via queries

**Comment by DavidBakerEffendi** [comment]
I've ticked what this PR would address: https://github.com/joernio/joern/pull/2928

Filtering on sources is a bit tricky, since the data-flow slicing is backward slicing, i.e. starts from a sink and goes backwards a set number of times. Depending on how far back it goes, it may never reach a source, so we can't always assume the last node in the backward slice is the source.

**Comment by prabhu** [comment]
@DavidBakerEffendi, Could we consider forward slicing (beginning from a source) as a future enhancement? We might encounter applications with only a few sources so that performance gains could be possible.

**Comment by prabhu** [comment]
This ticket could be considered as done since we have more than enough filters for v1.0.0 release.
